apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-namespace   # the namespace in the Supervisor, a.k.a. the vSphere Namespace — CHANGE_ME
resources:
  - ../../bases/velero
patches:
  - target:
      kind: VeleroService
      name: velero
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-namespace-velero
      - op: replace
        path: /spec/bucket
        value: example-bucket   # CHANGE_ME — see docs/03-required-platform-services.md
      - op: replace
        path: /spec/backuplocationconfig
        value: region=us-east-1,s3ForcePathStyle=true,s3Url=https://minio.example.internal:9000
